package app;

import java.util.List;

public class Actor extends Persona implements INominable {

    public boolean ganoPreviamente() {
        // base de datos
        return true;
    }

    public void reproducirTrailerNominacion() {
        System.out.println("Reproduciendo trailer de pelicula de "+ this.getNombre());
    }

    public void sacarSelfie(List<Actor> elenco) {
        // autogenerated
    }

    public boolean estaNominada() {
       
        return false;
    }
}